#!/bin/sh
# .git/hooks/prepare-commit-msg
# https://gist.github.com/bartoszmajsak/1396344
# feature/ISSUE-3 -> #3 feat: commit message

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(main develop release)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"
ISSUE_NUMBER=`echo $BRANCH_NAME | egrep -o "ISSUE-[0-9]+"`

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "$ISSUE_NUMBER" $1)

if [ -n $ISSUE_NUMBER ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s/^/#${ISSUE_NUMBER:6} /" $1
fi